language: c
before_install:
  # Download and install Arduino IDE environment
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  # Download Easyuino library from github master branch
  - wget https://github.com/Strabox/Easyuino/archive/master.zip
  - unzip master.zip
install:
  - ln -s master /usr/local/share/arduino/libraries/Easyuino
  - arduino --install-library "Easyuino"
script:
  - arduino --verify --board arduino:avr:uno $PWD/ArduinoControllerSerra/ArduinoControllerSerra.ino
notifications:
  email:
    on_success: change
    on_failure: change
